server:
  port: 8080
spring:
  cloud:
    config:
      profile: dev
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: data-service-cliente
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka/