server:
  port: 8765
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: naming-server
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
