server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: file:///home/lucasst/Área de Trabalho/TotalShake-Micro-Servicos/Micros serviços/git-localconfig-repo
  application:
    name: totalShake-config-server

