server:
  port: 8777
spring:
  cloud:
    config:
      profile: dev
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: api-pagamento
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka/
